### PR TITLE
Add July 20 notes

### PR DESCRIPTION
**Pull request by julen**
Any feedback welcome, thanks!

### CODE REVIEW

**Comment by unho** [comment]
Is there no list of which issues were triaged?

**Comment by dwaynebailey** [comment]
@julen thanks for these.  I was wondering if there was value in announcing the availability of these with some headline items.  Or for @unho to tweet when they are finalized?

**Comment by julen** [comment]
@unho to be honest personally I don't find much value in listing every single individual item because it doesn't say much for outsiders (GitHub's milestone page is probably the best place for that). My goal when I initiated this was to provide a view of what's being discussed and show the overall direction so that other people can get a feeling of what's going.

Of course, if you see that some specific issue is crucial and it's missing, we definitely want to put it in!

**Comment by julen** [comment]
As far as I'm present, I'm happy to take the notes @dwaynebailey. Further advertisement and community management... up to you, I don't have the time or the will for it!

**Comment by unho** [comment]
@julen Fair point, lgtm.

**Pull request merged**
